# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x1b\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tUserReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbb\x01\n\x05Users\x12\x31\n\x07GetUser\x12\x12.users.UserRequest\x1a\x10.users.UserReply\"\x00\x12>\n\x12GetUserStreamReply\x12\x12.users.UserRequest\x1a\x10.users.UserReply\"\x00\x30\x01\x12?\n\x11GetUserBidiStream\x12\x12.users.UserRequest\x1a\x10.users.UserReply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=22
  _globals['_USERREQUEST']._serialized_end=49
  _globals['_USERREPLY']._serialized_start=51
  _globals['_USERREPLY']._serialized_end=79
  _globals['_USERS']._serialized_start=82
  _globals['_USERS']._serialized_end=269
# @@protoc_insertion_point(module_scope)
